Validate`library-and-framework-list.json` with jq.

diff --git a/.github/workflows/library-and-framework-list-validation.yml b/.github/workflows/library-and-framework-list-validation.yml
--- a/.github/workflows/library-and-framework-list-validation.yml
+++ b/.github/workflows/library-and-framework-list-validation.yml
@@ -4,7 +4,7 @@ on: [push, pull_request]
 
 jobs:
   validate-library-and-framework-list-json:
-    name: "📋 Checks if the json file is written according to the existing schema"
+    name: "📋 Validate the JSON file"
     runs-on: "ubuntu-20.04"
     timeout-minutes: 5
     steps:
@@ -13,12 +13,19 @@ jobs:
       - uses: actions/setup-python@v4
         with:
           python-version: '3.10'
-      - run: pip install check-jsonschema
-      - run: check-jsonschema --schemafile library-and-framework-list-schema.json library-and-framework-list.json
-      - name: "🔧 Prepare environment"
-        uses: graalvm/setup-graalvm@v1
-        with:
-          version: 'latest'
-          java-version: '17'
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-      - run: ./gradlew spotlessJsonCheck
+      - name: Check that the JSON file is well-formatted and sorted by artifact
+        run: |
+          JSON="library-and-framework-list.json"
+          if ! jq -e . "${JSON}" >/dev/null; then
+            echo "'${JSON}' fails to parse. Please make sure it is a valid JSON file."
+            exit 6
+          fi
+          DIFF=$(diff "${JSON}" <(jq -s '.[] | sort_by(.artifact)' "${JSON}"))
+          if [[ -n "${DIFF}" ]]; then
+            echo "'${JSON}' is no longer sorted by artifact key. You can use 'jq' to sort it: 'sorted="$(jq -s '.[] | sort_by(.artifact)' ${JSON})" && echo -E "${sorted}" > ${JSON}"
+            exit 8
+          fi
+      - name: Check that the JSON file conforms to the schema
+        run: |
+          pip install check-jsonschema
+          check-jsonschema --schemafile library-and-framework-list-schema.json library-and-framework-list.json
